### PR TITLE
Document office API to manage offices & employees

### PR DESCRIPTION
**Pull request by Izakey**
Set up testing and document office API to manage offices & employee

### CODE REVIEW

**Comment by awasum** [comment]
For the EmployeeApiDocument,

Here are some issues I faced:

1)  In 'documentUpdateEmployee' :

"10:35:31.503 [qtp297785169-145] INFO  o.a.f.c.l.c.ServiceExceptionFilter - Responding with a service error ServiceError{code=409, message='Office myOffice already exists.'}

org.apache.fineract.cn.office.api.v1.client.AlreadyExistsException"

2) In documentCreateEmployee:

"org.springframework.web.util.NestedServletException: Request processing failed; nested exception is ServiceException{serviceError=ServiceError{code=409, message='Employee employ001 already exists.'}}"

3) In documentDeleteEmployee:


"10:35:40.614 [qtp297785169-146] INFO  o.a.f.c.l.c.ServiceExceptionFilter - Responding with a service error ServiceError{code=409, message='Office myOffice already exists.'}

org.apache.fineract.cn.office.api.v1.client.AlreadyExistsException"

**Comment by awasum** [comment]
OfficeApiDocumentation:

1) In documentAddExternalReference:
"java.lang.AssertionError: Status 
Expected :202
Actual   :400
"
2) in documentUpdateOffice
"10:57:44.856 [qtp842173892-144] INFO  o.a.f.c.l.c.ServiceExceptionFilter - Responding with a service error ServiceError{code=409, message='Office originalOffice already exists.'}

org.apache.fineract.cn.office.api.v1.client.AlreadyExistsException"

Try to see if you could make these better.

**Comment by Izakey** [comment]
Thanks very much Awasum, I've updated the PR with some fixes. I await your review.

**Comment by awasum** [comment]
Looks good. Merging now.

**Pull request merged**
